name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -leo pipefail {0} # required by setup-micromamba
    steps:
      - uses: actions/checkout@v4
      - name: Setup micromamba and uv
        uses: deargen/workflows/actions/setup-micromamba-and-uv@master
      - name: Cache Micromamba environment
        id: cache-micromamba
        uses: actions/cache@v4
        env:
          cache-name: cache-micromamba
        with:
          path: ~/micromamba/envs/test
          key: ${{ runner.os }}-micromamba-${{ env.cache-name }}-${{ hashFiles('deps/lock/x86_64-manylinux_2_28/requirements_dev.txt', '.github/workflows/tests.yml', 'pyproject.toml') }}
          # restore-keys: |
          #   ${{ runner.os }}-micromamba-${{ env.cache-name }}-
          #   ${{ runner.os }}-micromamba-
          #   ${{ runner.os }}-
      - if: steps.cache-micromamba.outputs.cache-hit == 'true'
        run: echo 'micromamba cache hit!'
      - name: Install dependencies
        if: steps.cache-micromamba.outputs.cache-hit != 'true'
        run: |
          uv pip install -r deps/lock/x86_64-manylinux_2_28/requirements_dev.txt
          uv pip install -e .
          bash scripts/install_binaries.sh
      - name: Run pytest
        uses: deargen/workflows/actions/run-pytest@master

  doctest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -leo pipefail {0} # required by setup-micromamba
    steps:
      - uses: actions/checkout@v4
      - name: Setup micromamba and uv
        uses: deargen/workflows/actions/setup-micromamba-and-uv@master
      - name: Cache Micromamba environment
        id: cache-micromamba
        uses: actions/cache@v4
        env:
          cache-name: cache-micromamba
        with:
          path: ~/micromamba/envs/test
          key: ${{ runner.os }}-micromamba-${{ env.cache-name }}-${{ hashFiles('deps/lock/x86_64-manylinux_2_28/requirements_dev.txt', '.github/workflows/tests.yml', 'pyproject.toml') }}
          # restore-keys: |
          #   ${{ runner.os }}-micromamba-${{ env.cache-name }}-
          #   ${{ runner.os }}-micromamba-
          #   ${{ runner.os }}-
      - if: steps.cache-micromamba.outputs.cache-hit == 'true'
        run: echo 'micromamba cache hit!'
      - name: Install dependencies
        if: steps.cache-micromamba.outputs.cache-hit != 'true'
        run: |
          uv pip install -r deps/lock/x86_64-manylinux_2_28/requirements_dev.txt
          uv pip install -e .
          bash scripts/install_binaries.sh
      - name: Run doctest
        uses: deargen/workflows/actions/run-doctest@master
